<?php
declare(strict_types=1);

function render_structure_page(): never
{
    require_management_mode();
    $section = $_GET['section'] ?? 'years';
    $years = rows('SELECT * FROM school_years ORDER BY starts_on DESC');
    $periods = rows('SELECT p.*,y.name year_name FROM periods p JOIN school_years y ON y.id=p.school_year_id ORDER BY y.starts_on DESC,p.sort_order');
    $subperiods = rows('SELECT * FROM period_subperiods ORDER BY period_id,sort_order,starts_on');
    $principals = rows("SELECT id,name FROM users WHERE (can_be_principal=1 OR role='admin') AND active=1 ORDER BY name");
    $teachers = rows('SELECT id,name FROM users WHERE can_teach=1 AND active=1 ORDER BY last_name,first_name,name');
    $classes = rows("SELECT c.*,y.name year_name,(SELECT GROUP_CONCAT(u.name ORDER BY u.name SEPARATOR ', ') FROM class_principals cp JOIN users u ON u.id=cp.user_id WHERE cp.class_id=c.id) principal,(SELECT GROUP_CONCAT(cp.user_id ORDER BY cp.user_id) FROM class_principals cp WHERE cp.class_id=c.id) principal_ids FROM classes c JOIN school_years y ON y.id=c.school_year_id ORDER BY y.starts_on DESC,c.sort_order,c.level");
    $subjects = rows('SELECT * FROM subjects ORDER BY name');
    $groups = rows('SELECT cg.*,c.name class_name,c.level,y.name year_name,COUNT(gs.student_id) student_count FROM class_groups cg JOIN classes c ON c.id=cg.class_id JOIN school_years y ON y.id=c.school_year_id LEFT JOIN group_students gs ON gs.group_id=cg.id GROUP BY cg.id ORDER BY y.starts_on DESC,c.sort_order,cg.name');
    $selectedGroupId = (int)($_GET['group_id'] ?? 0);
    $selectedGroup = $selectedGroupId ? one('SELECT cg.*,c.level,y.name year_name FROM class_groups cg JOIN classes c ON c.id=cg.class_id JOIN school_years y ON y.id=c.school_year_id WHERE cg.id=?', [$selectedGroupId]) : null;
    $groupStudents = $selectedGroup ? rows('SELECT s.id,s.last_name,s.first_name,IF(gs.student_id IS NULL,0,1) selected FROM enrollments e JOIN students s ON s.id=e.student_id LEFT JOIN group_students gs ON gs.student_id=s.id AND gs.group_id=? WHERE e.class_id=? AND s.active=1 ORDER BY s.last_name,s.first_name', [$selectedGroupId,$selectedGroup['class_id']]) : [];
    $assignments = rows("SELECT co.id,co.class_id,co.subject_id,co.class_group_id,co.assignment_coefficient,co.display_order,c.name class_name,c.level,y.name year_name,s.name subject,cg.name group_label,MAX(CASE WHEN ct.assignment_role='lead' THEN ct.user_id END) lead_teacher_id,MAX(CASE WHEN ct.assignment_role='co_teacher' THEN ct.user_id END) co_teacher_id,GROUP_CONCAT(CASE WHEN ct.assignment_role IN ('lead','co_teacher') THEN CONCAT(u.name,IF(ct.assignment_role='co_teacher',' (co-professeur)','')) END ORDER BY ct.assignment_role DESC SEPARATOR ', ') teachers FROM courses co JOIN classes c ON c.id=co.class_id JOIN school_years y ON y.id=c.school_year_id JOIN subjects s ON s.id=co.subject_id LEFT JOIN class_groups cg ON cg.id=co.class_group_id LEFT JOIN course_teachers ct ON ct.course_id=co.id LEFT JOIN users u ON u.id=ct.user_id GROUP BY co.id ORDER BY y.starts_on DESC,c.level,c.name,co.display_order,s.name");
    $selectedClassId = (int)($_GET['class_id'] ?? ($classes[0]['id'] ?? 0));
    header_html('Organisation scolaire');
    ?><link rel="stylesheet" href="assets/structure.css?v=103">
    <nav class="structure-tabs"><?php foreach (['years' => 'Années & périodes','classes' => 'Classes','groups' => 'Groupes','subjects' => 'Matières','assignments' => 'Affectations'] as $key => $label):?><a class="<?=$section === $key ? 'active' : ''?>" href="?page=structure&section=<?=$key?>"><?=e($label)?></a><?php endforeach?></nav>
    <?php if ($section === 'years'):?>
      <?php if (is_admin()):?><form class="panel" method="post"><div class="panel-head"><div><p class="eyebrow">Référence de l’établissement</p><h2>Année scolaire active</h2><p class="muted">Elle détermine les niveaux, affectations et carnets de notes proposés.</p></div><button>Définir comme active</button></div><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="set_active_year"><label>Année active<select required name="year_id"><?php foreach ($years as $year):?><option value="<?=$year['id']?>" <?=$year['active'] ? 'selected' : ''?>><?=e($year['name'])?></option><?php endforeach?></select></label></form><?php endif?>
      <?php render_school_years_section($years, $periods, $subperiods);?>
    <?php elseif ($section === 'classes'):?>
      <?php render_levels_section_with_stage($classes, $years, $principals);?>
    <?php elseif ($section === 'classes_legacy'):?>
      <div class="two-col"><section class="panel"><p class="eyebrow">Niveaux ordonnés de 1 à 12</p><h2>Niveaux scolaires</h2><?php foreach ($classes as $class):?><form class="structure-row" method="post"><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="update_class"><input type="hidden" name="class_id" value="<?=$class['id']?>"><input name="level" required value="<?=e($class['level'])?>"><input name="sort_order" type="number" min="1" max="12" value="<?=$class['sort_order']?>" title="Ordre de 1 à 12"><select name="principal_user_id"><option value="">Sans professeur principal</option><?php foreach ($principals as $principal):?><option value="<?=$principal['id']?>" <?=$class['principal_user_id'] === $principal['id'] ? 'selected' : ''?>><?=e($principal['name'])?></option><?php endforeach?></select><div class="structure-row-actions"><button>Modifier</button><button class="danger-button" type="submit" name="action" value="delete_class" formnovalidate onclick="return confirm('Supprimer définitivement ce niveau vide ?');">Supprimer</button></div></form><?php endforeach?></section><form class="panel sticky" method="post"><h2>Créer un niveau</h2><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="add_class"><label>Année scolaire<select name="school_year_id"><?php foreach ($years as $year):?><option value="<?=$year['id']?>"><?=e($year['name'])?></option><?php endforeach?></select></label><label>Niveau<input required name="level" placeholder="4e"></label><label>Ordre pédagogique <small>(de 1 à 12)</small><input required type="number" min="1" max="12" name="sort_order" value="1"></label><label>Professeur principal / instituteur<select name="principal_user_id"><option value="">Non affecté</option><?php foreach ($principals as $principal):?><option value="<?=$principal['id']?>"><?=e($principal['name'])?></option><?php endforeach?></select></label><button>Créer le niveau</button></form></div>
    <?php elseif ($section === 'groups'):?>
      <?php render_groups_section($classes, $groups, $selectedGroup, $selectedGroupId, $groupStudents);?>
    <?php elseif ($section === 'groups_legacy'):?>
      <div class="two-col">
        <section>
          <form class="panel" method="post"><p class="eyebrow">Organisation des élèves</p><h2>Créer un groupe</h2><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="add_group"><label>Niveau<select required name="class_id"><?php foreach ($classes as $class):?><option value="<?=$class['id']?>"><?=e($class['year_name'].' · '.$class['level'])?></option><?php endforeach?></select></label><label>Nom du groupe<input required name="name" placeholder="Groupe A"></label><button>Créer le groupe</button></form>
          <section class="panel"><div class="panel-head"><div><p class="eyebrow">Groupes constitués</p><h2>Groupes existants</h2></div><span class="badge"><?=count($groups)?></span></div><?php foreach ($groups as $group):?><a class="group-row <?=$selectedGroupId === (int)$group['id'] ? 'selected' : ''?>" href="?page=structure&amp;section=groups&amp;group_id=<?=$group['id']?>"><span><strong><?=e($group['name'])?></strong><small><?=e($group['year_name'].' · '.$group['level'])?></small></span><span><?=e($group['student_count'])?> élève(s)</span></a><?php endforeach?><?php if (!$groups):?><p class="empty">Aucun groupe créé.</p><?php endif?></section>
        </section>
        <section>
          <?php if ($selectedGroup):?><form class="panel sticky" method="post"><p class="eyebrow"><?=e($selectedGroup['year_name'].' · '.$selectedGroup['level'])?></p><h2>Élèves — <?=e($selectedGroup['name'])?></h2><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="save_group_students"><input type="hidden" name="group_id" value="<?=$selectedGroupId?>"><div class="student-checklist"><?php foreach ($groupStudents as $student):?><label class="check"><input type="checkbox" name="student_ids[]" value="<?=$student['id']?>" <?=$student['selected'] ? 'checked' : ''?>> <?=e($student['last_name'].' '.$student['first_name'])?></label><?php endforeach?></div><?php if (!$groupStudents):?><p class="empty">Aucun élève n’est inscrit dans ce niveau.</p><?php endif?><button>Enregistrer la composition</button></form><?php else:?><div class="panel empty-state"><h2>Composer un groupe</h2><p>Sélectionnez un groupe dans la liste pour ajouter ou retirer rapidement des élèves.</p></div><?php endif?>
        </section>
      </div>
    <?php elseif ($section === 'subjects'):?>
      <?php render_subjects_section($subjects);?>
    <?php elseif ($section === 'subjects_legacy'):?>
      <div class="two-col"><section class="panel"><p class="eyebrow">Référentiel pédagogique</p><h2>Matières</h2><?php foreach ($subjects as $subject):?><div class="structure-row"><strong><?=e($subject['name'])?></strong><span class="tag">Coefficient par défaut <?=e($subject['coefficient'])?></span></div><?php endforeach?><a class="button secondary structure-edit" href="?page=admin-management&tab=subjects">Modifier les matières existantes</a></section><form class="panel sticky" method="post"><h2>Créer une matière</h2><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="add_subject"><label>Nom de la matière<input required name="name" placeholder="Mathématiques"></label><label>Coefficient par défaut<input required type="number" min="0.01" step="0.01" name="coefficient" value="1"></label><button>Créer la matière</button></form></div>
    <?php elseif ($section === 'assignments'):?>
      <?php render_assignments_section_compact($assignments, $selectedClassId, $classes, $groups, $subjects, $teachers);?>
    <?php else:?>
      <section class="panel assignment-intro"><p class="eyebrow">Module administrateur</p><h2>Affectations pédagogiques</h2><div class="panel-head"><form method="get"><input type="hidden" name="page" value="structure"><input type="hidden" name="section" value="assignments"><label>Niveau<select name="class_id" onchange="this.form.submit()"><?php foreach ($classes as $class):?><option value="<?=$class['id']?>" <?=$selectedClassId === $class['id'] ? 'selected' : ''?>><?=e($class['year_name'].' · '.$class['level'])?></option><?php endforeach?></select></label></form><div class="actions"><a class="button secondary" href="?page=structure&section=groups">Composer les groupes</a><a class="button secondary" href="?page=users">Gérer les enseignants</a></div></div></section>
      <section class="panel"><div class="table-wrap"><table><thead><tr><th>Ordre</th><th>Matière</th><th>Public</th><th>Professeur(s)</th><th>Coefficient</th><th>Modification</th></tr></thead><tbody><?php foreach ($assignments as $assignment):if ((int)$assignment['class_id'] !== $selectedClassId) {
          continue;
      }?><tr><td><?=$assignment['display_order']?></td><td><strong><?=e($assignment['subject'])?></strong></td><td><?=e($assignment['group_label'] ?: 'Niveau entier')?></td><td><?=e($assignment['teachers'] ?: 'Sans enseignant')?></td><td><?=e($assignment['assignment_coefficient'])?></td><td><details><summary>Modifier</summary><?php render_assignment_form($assignment, $classes, $groups, $subjects, $teachers);?></details></td></tr><?php endforeach?></tbody></table></div></section><section class="panel"><p class="eyebrow">Nouvelle affectation</p><h2>Ajouter une matière au niveau ou à un groupe</h2><?php render_assignment_form(null, $classes, $groups, $subjects, $teachers);?></section>
    <?php endif?>
    <?php footer_html();
    exit;
}

function render_school_years_section(array $years, array $periods, array $subperiods): void
{
    $editPeriodId = (int) ($_GET['edit_period'] ?? 0);
    $editSubperiodId = (int) ($_GET['edit_subperiod'] ?? 0);
    $editPeriod = current(array_filter($periods, fn (array $item): bool => (int) $item['id'] === $editPeriodId)) ?: null;
    $editSubperiod = current(array_filter($subperiods, fn (array $item): bool => (int) $item['id'] === $editSubperiodId)) ?: null;
    ?>
    <div class="two-col school-years-layout">
        <section class="panel">
            <p class="eyebrow">Calendrier pédagogique</p><h2>Années scolaires et trimestres</h2>
            <?php foreach ($years as $year): ?>
                <div class="structure-row"><span><strong><?= e($year['name']) ?></strong><small><?= date('d/m/Y', strtotime($year['starts_on'])) ?> → <?= date('d/m/Y', strtotime($year['ends_on'])) ?></small></span><?= $year['active'] ? '<span class="tag">Active</span>' : '' ?></div>
                <?php foreach ($periods as $period): if ((int) $period['school_year_id'] !== (int) $year['id']) {
                    continue;
                } ?>
                    <div class="period-management-row">
                        <span><strong><?= e($period['name']) ?></strong><small><?= date('d/m/Y', strtotime($period['starts_on'])) ?> → <?= date('d/m/Y', strtotime($period['ends_on'])) ?></small></span>
                        <span class="tag"><?= $period['status'] === 'open' ? 'Ouvert' : 'Fermé' ?></span>
                        <span class="table-actions"><a class="icon-button" href="?page=structure&amp;section=years&amp;edit_period=<?= $period['id'] ?>" title="Modifier" aria-label="Modifier"><i class="bi bi-pencil-square"></i></a><form method="post" onsubmit="return confirm('Supprimer ce trimestre vide et ses sous-périodes ?')"><input type="hidden" name="_token" value="<?= csrf() ?>"><input type="hidden" name="action" value="delete_period"><input type="hidden" name="period_id" value="<?= $period['id'] ?>"><button class="icon-button danger" title="Supprimer" aria-label="Supprimer"><i class="bi bi-trash"></i></button></form></span>
                    </div>
                    <div class="subperiod-list">
                    <?php foreach ($subperiods as $subperiod): if ((int) $subperiod['period_id'] !== (int) $period['id']) {
                        continue;
                    } ?>
                        <div class="subperiod-row"><span><strong><?= e($subperiod['name']) ?></strong><small><?= date('d/m/Y', strtotime($subperiod['starts_on'])) ?> → <?= date('d/m/Y', strtotime($subperiod['ends_on'])) ?></small></span><span class="table-actions"><a class="icon-button" href="?page=structure&amp;section=years&amp;edit_subperiod=<?= $subperiod['id'] ?>" title="Modifier" aria-label="Modifier"><i class="bi bi-pencil-square"></i></a><form method="post" onsubmit="return confirm('Supprimer cette sous-période ?')"><input type="hidden" name="_token" value="<?= csrf() ?>"><input type="hidden" name="action" value="delete_subperiod"><input type="hidden" name="subperiod_id" value="<?= $subperiod['id'] ?>"><button class="icon-button danger" title="Supprimer" aria-label="Supprimer"><i class="bi bi-trash"></i></button></form></span></div>
                    <?php endforeach; ?>
                    </div>
                    <details class="subperiod-create"><summary>Ajouter une sous-période</summary><form method="post"><input type="hidden" name="_token" value="<?= csrf() ?>"><input type="hidden" name="action" value="add_subperiod"><input type="hidden" name="period_id" value="<?= $period['id'] ?>"><label>Nom<input required name="name" placeholder="Mi-trimestre"></label><div class="form-row"><label>Début<input required type="date" name="starts_on" min="<?= $period['starts_on'] ?>" max="<?= $period['ends_on'] ?>"></label><label>Fin<input required type="date" name="ends_on" min="<?= $period['starts_on'] ?>" max="<?= $period['ends_on'] ?>"></label></div><label>Ordre<input type="number" min="1" name="sort_order" value="1"></label><button>Créer la sous-période</button></form></details>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </section>
        <section>
            <?php if ($editSubperiod): ?>
                <form class="panel" method="post"><p class="eyebrow">Modification</p><h2>Modifier la sous-période</h2><input type="hidden" name="_token" value="<?= csrf() ?>"><input type="hidden" name="action" value="update_subperiod"><input type="hidden" name="subperiod_id" value="<?= $editSubperiod['id'] ?>"><input type="hidden" name="period_id" value="<?= $editSubperiod['period_id'] ?>"><label>Nom<input required name="name" value="<?= e($editSubperiod['name']) ?>"></label><div class="form-row"><label>Début<input required type="date" name="starts_on" value="<?= $editSubperiod['starts_on'] ?>"></label><label>Fin<input required type="date" name="ends_on" value="<?= $editSubperiod['ends_on'] ?>"></label></div><label>Ordre<input type="number" min="1" name="sort_order" value="<?= $editSubperiod['sort_order'] ?>"></label><div class="actions"><a class="button secondary" href="?page=structure&amp;section=years">Annuler</a><button>Enregistrer</button></div></form>
            <?php elseif ($editPeriod): ?>
                <form class="panel" method="post"><p class="eyebrow">Modification</p><h2>Modifier le trimestre</h2><input type="hidden" name="_token" value="<?= csrf() ?>"><input type="hidden" name="action" value="update_period"><input type="hidden" name="period_id" value="<?= $editPeriod['id'] ?>"><label>Nom<input required name="name" value="<?= e($editPeriod['name']) ?>"></label><div class="form-row"><label>Début<input required type="date" name="starts_on" value="<?= $editPeriod['starts_on'] ?>"></label><label>Fin<input required type="date" name="ends_on" value="<?= $editPeriod['ends_on'] ?>"></label></div><div class="form-row"><label>Ouverture saisie<input type="date" name="entry_opens_on" value="<?= $editPeriod['entry_opens_on'] ?>"></label><label>Fermeture saisie<input type="date" name="entry_closes_on" value="<?= $editPeriod['entry_closes_on'] ?>"></label></div><div class="form-row"><label>État<select name="status"><option value="open" <?= $editPeriod['status'] === 'open' ? 'selected' : '' ?>>Ouvert</option><option value="closed" <?= $editPeriod['status'] !== 'open' ? 'selected' : '' ?>>Fermé</option></select></label><label>Ordre<input type="number" min="1" name="sort_order" value="<?= $editPeriod['sort_order'] ?>"></label></div><div class="actions"><a class="button secondary" href="?page=structure&amp;section=years">Annuler</a><button>Enregistrer</button></div></form>
            <?php else: ?>
                <form class="panel" method="post"><h2>Préparer une nouvelle année</h2><input type="hidden" name="_token" value="<?= csrf() ?>"><input type="hidden" name="action" value="prepare_school_year"><label>Année source<select name="source_year_id"><?php foreach ($years as $year): ?><option value="<?= $year['id'] ?>"><?= e($year['name']) ?></option><?php endforeach; ?></select></label><label>Nouvelle année<input required name="name" placeholder="2027-2028"></label><div class="form-row"><label>Début<input required type="date" name="starts_on"></label><label>Fin<input required type="date" name="ends_on"></label></div><button>Créer, promouvoir et recopier les affectations</button></form>
                <form class="panel" method="post"><h2>Créer un trimestre</h2><input type="hidden" name="_token" value="<?= csrf() ?>"><input type="hidden" name="action" value="add_period"><label>Année<select name="school_year_id"><?php foreach ($years as $year): ?><option value="<?= $year['id'] ?>"><?= e($year['name']) ?></option><?php endforeach; ?></select></label><label>Nom<input required name="name" placeholder="Trimestre 1"></label><div class="form-row"><label>Début<input required type="date" name="starts_on"></label><label>Fin<input required type="date" name="ends_on"></label></div><div class="form-row"><label>Ouverture saisie<input type="date" name="entry_opens_on"></label><label>Fermeture saisie<input type="date" name="entry_closes_on"></label></div><div class="form-row"><label>État<select name="status"><option value="closed">Fermé</option><option value="open">Ouvert</option></select></label><label>Ordre<input type="number" min="1" name="sort_order" value="1"></label></div><button>Créer le trimestre</button></form>
            <?php endif; ?>
        </section>
    </div>
    <?php
}

function render_assignment_form(?array $assignment, array $classes, array $groups, array $subjects, array $teachers, int $preferredClassId = 0): void
{
    $isEdit = $assignment !== null;
    ?><form class="assignment-form" method="post"><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="save_assignment"><input type="hidden" name="assignment_id" value="<?=$assignment['id'] ?? 0?>"><?php if ($isEdit):?><input type="hidden" name="class_id" value="<?=$assignment['class_id']?>"><input type="hidden" name="subject_id" value="<?=$assignment['subject_id']?>"><?php else:?><label>Niveau<select required name="class_id" data-assignment-class><?php foreach ($classes as $class):?><option value="<?=$class['id']?>" <?=$preferredClassId > 0 && $preferredClassId === (int)$class['id'] ? 'selected' : ''?>><?=e($class['level'].' · '.$class['year_name'])?></option><?php endforeach?></select></label><label>Matière<select required name="subject_id"><?php foreach ($subjects as $subject):?><option value="<?=$subject['id']?>"><?=e($subject['name'])?></option><?php endforeach?></select></label><?php endif?><label>Public concerné<select name="class_group_id"><option value="">Niveau entier</option><?php foreach ($groups as $group):if ($isEdit && (int)$group['class_id'] !== (int)$assignment['class_id']) {
        continue;
    }?><option value="<?=$group['id']?>" data-class-id="<?=$group['class_id']?>" <?=($assignment['class_group_id'] ?? null) === $group['id'] ? 'selected' : ''?>><?=e($group['name'])?></option><?php endforeach?></select></label><div class="form-row"><label>Professeur<select required name="lead_teacher_id"><option value="">Choisir</option><?php foreach ($teachers as $teacher):?><option value="<?=$teacher['id']?>" <?=($assignment['lead_teacher_id'] ?? null) === $teacher['id'] ? 'selected' : ''?>><?=e($teacher['name'])?></option><?php endforeach?></select></label><label>Co-professeur<select name="co_teacher_id"><option value="">Aucun</option><?php foreach ($teachers as $teacher):?><option value="<?=$teacher['id']?>" <?=($assignment['co_teacher_id'] ?? null) === $teacher['id'] ? 'selected' : ''?>><?=e($teacher['name'])?></option><?php endforeach?></select></label></div><div class="form-row"><label>Coefficient<input required type="number" min="0.01" step="0.01" name="assignment_coefficient" value="<?=e($assignment['assignment_coefficient'] ?? 1)?>"></label><label>Ordre sur le bulletin<input required type="number" min="1" step="1" name="display_order" value="<?=e($assignment['display_order'] ?? 100)?>"></label></div><button><?=$isEdit ? 'Enregistrer les modifications' : 'Créer l’affectation'?></button></form><?php
}

function render_levels_section(array $classes, array $years, array $principals): void
{
    $editId = (int)($_GET['edit_class'] ?? 0);
    $edit = null;
    foreach ($classes as $item) {
        if ((int)$item['id'] === $editId) {
            $edit = $item;
        }
    }
    ?><div class="two-col"><section class="panel"><p class="eyebrow">Niveaux ordonnés de 1 à 12</p><h2>Niveaux scolaires</h2><div class="table-wrap"><table><thead><tr><th>Niveau</th><th>Ordre</th><th>Professeur principal / instituteur</th><th>Actions</th></tr></thead><tbody><?php foreach ($classes as $class):?><tr><td><strong><?=e($class['level'])?></strong></td><td><?=e($class['sort_order'])?></td><td><?=e($class['principal'] ?: 'Non affecté')?></td><td><span class="table-actions"><a class="icon-button" href="?page=structure&amp;section=classes&amp;edit_class=<?=$class['id']?>" title="Modifier" aria-label="Modifier"><i class="bi bi-pencil-square"></i></a><form method="post" onsubmit="return confirm('Supprimer définitivement ce niveau vide ?')"><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_class"><input type="hidden" name="class_id" value="<?=$class['id']?>"><button class="icon-button danger" title="Supprimer" aria-label="Supprimer"><i class="bi bi-trash"></i></button></form></span></td></tr><?php endforeach?></tbody></table></div></section>
    <form class="panel sticky" method="post"><p class="eyebrow"><?=$edit ? 'Modification' : 'Création'?></p><h2><?=$edit ? 'Modifier le niveau' : 'Créer un niveau'?></h2><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="<?=$edit ? 'update_class' : 'add_class'?>"><?php if ($edit):?><input type="hidden" name="class_id" value="<?=$edit['id']?>"><?php else:?><label>Année scolaire<select name="school_year_id"><?php foreach ($years as $year):?><option value="<?=$year['id']?>"><?=e($year['name'])?></option><?php endforeach?></select></label><?php endif?><label>Niveau<input required name="level" value="<?=e($edit['level'] ?? '')?>" placeholder="CE1"></label><label>Ordre pédagogique <small>(de 1 à 12)</small><input required type="number" min="1" max="12" name="sort_order" value="<?=e($edit['sort_order'] ?? 1)?>"></label><label>Professeur principal / instituteur<select name="principal_user_id"><option value="">Non affecté</option><?php foreach ($principals as $principal):?><option value="<?=$principal['id']?>" <?=($edit['principal_user_id'] ?? null) === $principal['id'] ? 'selected' : ''?>><?=e($principal['name'])?></option><?php endforeach?></select></label><div class="actions"><?php if ($edit):?><a class="button secondary" href="?page=structure&amp;section=classes">Annuler</a><?php endif?><button><?=$edit ? 'Enregistrer' : 'Créer le niveau'?></button></div></form></div><?php
}

function render_levels_section_with_stage(array $classes, array $years, array $principals): void
{
    $editId = (int)($_GET['edit_class'] ?? 0);
    $edit = null;
    foreach ($classes as $item) {
        if ((int)$item['id'] === $editId) {
            $edit = $item;
        }
    }
    $stageLabels = ['preschool' => 'Maternelle','primary' => 'Primaire','middle' => 'Collège'];
    ?><div class="two-col"><section class="panel"><p class="eyebrow">Niveaux ordonnés de 1 à 12</p><h2>Niveaux scolaires</h2><div class="table-wrap"><table><thead><tr><th>Niveau</th><th>Cycle</th><th>Ordre</th><th>Instituteur / professeur principal</th><th>Actions</th></tr></thead><tbody><?php foreach ($classes as $class):?><tr><td><strong><?=e($class['level'])?></strong></td><td><span class="tag"><?=e($stageLabels[$class['education_stage'] ?? 'primary'])?></span></td><td><?=e($class['sort_order'])?></td><td><?=e($class['principal'] ?: 'Non affecté')?></td><td><span class="table-actions"><a class="icon-button" href="?page=structure&amp;section=classes&amp;edit_class=<?=$class['id']?>" title="Modifier" aria-label="Modifier"><i class="bi bi-pencil-square"></i></a><form method="post" onsubmit="return confirm('Supprimer définitivement ce niveau vide ?')"><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_class"><input type="hidden" name="class_id" value="<?=$class['id']?>"><button class="icon-button danger" title="Supprimer" aria-label="Supprimer"><i class="bi bi-trash"></i></button></form></span></td></tr><?php endforeach?></tbody></table></div></section>
    <?php $selectedPrincipalIds = array_filter(array_map('intval', explode(',', (string) ($edit['principal_ids'] ?? '')))); ?>
    <form class="panel sticky" method="post"><p class="eyebrow"><?=$edit ? 'Modification' : 'Création'?></p><h2><?=$edit ? 'Modifier le niveau' : 'Créer un niveau'?></h2><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="<?=$edit ? 'update_class' : 'add_class'?>"><?php if ($edit):?><input type="hidden" name="class_id" value="<?=$edit['id']?>"><?php else:?><label>Année scolaire<select name="school_year_id"><?php foreach ($years as $year):?><option value="<?=$year['id']?>"><?=e($year['name'])?></option><?php endforeach?></select></label><?php endif?><label>Niveau<input required name="level" value="<?=e($edit['level'] ?? '')?>" placeholder="CE1"></label><label>Cycle scolaire<select required name="education_stage"><?php foreach ($stageLabels as $key => $label):?><option value="<?=$key?>" <?=($edit['education_stage'] ?? 'primary') === $key ? 'selected' : ''?>><?=e($label)?></option><?php endforeach?></select></label><label>Ordre pédagogique <small>(de 1 à 12)</small><input required type="number" min="1" max="12" name="sort_order" value="<?=e($edit['sort_order'] ?? 1)?>"></label><fieldset><legend>Instituteur(s) / professeur(s) principal(aux)</legend><div class="student-checklist principal-checklist"><?php foreach ($principals as $principal):?><label class="check"><input type="checkbox" name="principal_user_ids[]" value="<?=$principal['id']?>" <?=in_array((int) $principal['id'], $selectedPrincipalIds, true) ? 'checked' : ''?>> <?=e($principal['name'])?></label><?php endforeach?></div><small>Vous pouvez sélectionner une ou plusieurs personnes.</small></fieldset><div class="actions"><?php if ($edit):?><a class="button secondary" href="?page=structure&amp;section=classes">Annuler</a><?php endif?><button><?=$edit ? 'Enregistrer' : 'Créer le niveau'?></button></div></form></div><?php
}

function render_groups_section(array $classes, array $groups, ?array $selectedGroup, int $selectedGroupId, array $groupStudents): void
{
    $editId = (int)($_GET['edit_group'] ?? 0);
    $edit = null;
    foreach ($groups as $item) {
        if ((int)$item['id'] === $editId) {
            $edit = $item;
        }
    }
    ?><div class="two-col"><section><section class="panel"><p class="eyebrow">Groupes constitués</p><h2>Groupes</h2><div class="table-wrap"><table><thead><tr><th>Groupe</th><th>Niveau</th><th>Élèves</th><th>Actions</th></tr></thead><tbody><?php foreach ($groups as $group):?><tr><td><a href="?page=structure&amp;section=groups&amp;group_id=<?=$group['id']?>"><strong><?=e($group['name'])?></strong></a></td><td><?=e($group['level'])?></td><td><?=e($group['student_count'])?></td><td><span class="table-actions"><a class="icon-button" href="?page=structure&amp;section=groups&amp;group_id=<?=$group['id']?>&amp;edit_group=<?=$group['id']?>" title="Modifier" aria-label="Modifier"><i class="bi bi-pencil-square"></i></a><form method="post" onsubmit="return confirm('Supprimer ce groupe ?')"><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_group"><input type="hidden" name="group_id" value="<?=$group['id']?>"><button class="icon-button danger" title="Supprimer" aria-label="Supprimer"><i class="bi bi-trash"></i></button></form></span></td></tr><?php endforeach?></tbody></table></div></section>
    <form class="panel" method="post"><p class="eyebrow"><?=$edit ? 'Modification' : 'Création'?></p><h2><?=$edit ? 'Modifier le groupe' : 'Créer un groupe'?></h2><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="<?=$edit ? 'update_group' : 'add_group'?>"><?php if ($edit):?><input type="hidden" name="group_id" value="<?=$edit['id']?>"><p><strong>Niveau :</strong> <?=e($edit['level'])?></p><?php else:?><label>Niveau<select required name="class_id"><?php foreach ($classes as $class):?><option value="<?=$class['id']?>"><?=e($class['level'])?></option><?php endforeach?></select></label><?php endif?><label>Nom du groupe<input required name="name" value="<?=e($edit['name'] ?? '')?>" placeholder="Groupe A"></label><div class="actions"><?php if ($edit):?><a class="button secondary" href="?page=structure&amp;section=groups&amp;group_id=<?=$edit['id']?>">Annuler</a><?php endif?><button><?=$edit ? 'Enregistrer' : 'Créer'?></button></div></form></section>
    <section><?php if ($selectedGroup):?><form class="panel sticky" method="post"><p class="eyebrow"><?=e($selectedGroup['level'])?></p><h2>Élèves — <?=e($selectedGroup['name'])?></h2><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="save_group_students"><input type="hidden" name="group_id" value="<?=$selectedGroupId?>"><div class="student-checklist"><?php foreach ($groupStudents as $student):?><label class="check"><input type="checkbox" name="student_ids[]" value="<?=$student['id']?>" <?=$student['selected'] ? 'checked' : ''?>> <?=e($student['last_name'].' '.$student['first_name'])?></label><?php endforeach?></div><button>Enregistrer la composition</button></form><?php else:?><div class="panel empty-state"><h2>Composer un groupe</h2><p>Sélectionnez son nom dans le tableau.</p></div><?php endif?></section></div><?php
}

function render_subjects_section(array $subjects): void
{
    $editId = (int)($_GET['edit_subject'] ?? 0);
    $edit = null;
    foreach ($subjects as $item) {
        if ((int)$item['id'] === $editId) {
            $edit = $item;
        }
    }
    ?><div class="two-col"><section class="panel"><p class="eyebrow">Référentiel pédagogique</p><h2>Matières</h2><div class="table-wrap"><table><thead><tr><th>Matière</th><th>Coefficient par défaut</th><th>Actions</th></tr></thead><tbody><?php foreach ($subjects as $subject):?><tr><td><strong><?=e($subject['name'])?></strong></td><td><?=e($subject['coefficient'])?></td><td><span class="table-actions"><a class="icon-button" href="?page=structure&amp;section=subjects&amp;edit_subject=<?=$subject['id']?>" title="Modifier" aria-label="Modifier"><i class="bi bi-pencil-square"></i></a><form method="post" onsubmit="return confirm('Supprimer cette matière ?')"><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_subject"><input type="hidden" name="subject_id" value="<?=$subject['id']?>"><button class="icon-button danger" title="Supprimer" aria-label="Supprimer"><i class="bi bi-trash"></i></button></form></span></td></tr><?php endforeach?></tbody></table></div></section><form class="panel sticky" method="post"><p class="eyebrow"><?=$edit ? 'Modification' : 'Création'?></p><h2><?=$edit ? 'Modifier la matière' : 'Créer une matière'?></h2><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="<?=$edit ? 'update_subject' : 'add_subject'?>"><?php if ($edit):?><input type="hidden" name="subject_id" value="<?=$edit['id']?>"><?php endif?><label>Nom<input required name="name" value="<?=e($edit['name'] ?? '')?>"></label><label>Coefficient par défaut<input required type="number" min="0.01" step="0.01" name="coefficient" value="<?=e($edit['coefficient'] ?? 1)?>"></label><div class="actions"><?php if ($edit):?><a class="button secondary" href="?page=structure&amp;section=subjects">Annuler</a><?php endif?><button><?=$edit ? 'Enregistrer' : 'Créer'?></button></div></form></div><?php
}

function render_assignments_section(array $assignments, int $classId, array $classes, array $groups, array $subjects, array $teachers): void
{
    $editId = (int)($_GET['edit_assignment'] ?? 0);
    $edit = null;
    foreach ($assignments as $item) {
        if ((int)$item['id'] === $editId) {
            $edit = $item;
        }
    }
    ?><section class="panel assignment-intro"><p class="eyebrow">Module administrateur</p><h2>Affectations pédagogiques</h2><form method="get"><input type="hidden" name="page" value="structure"><input type="hidden" name="section" value="assignments"><label>Niveau<select name="class_id" onchange="this.form.submit()"><?php foreach ($classes as $class):?><option value="<?=$class['id']?>" <?=$classId === (int)$class['id'] ? 'selected' : ''?>><?=e($class['level'])?></option><?php endforeach?></select></label></form></section>
    <section class="panel"><div class="table-wrap"><table><thead><tr><th>Ordre</th><th>Matière</th><th>Public</th><th>Professeur(s)</th><th>Coefficient</th><th>Actions</th></tr></thead><tbody><?php foreach ($assignments as $assignment):if ((int)$assignment['class_id'] !== $classId) {
        continue;
    }?><tr><td><?=e($assignment['display_order'])?></td><td><strong><?=e($assignment['subject'])?></strong></td><td><?=e($assignment['group_label'] ?: 'Niveau entier')?></td><td><?=e($assignment['teachers'] ?: 'Sans enseignant')?></td><td><?=e($assignment['assignment_coefficient'])?></td><td><span class="table-actions"><a class="icon-button" href="?page=structure&amp;section=assignments&amp;class_id=<?=$classId?>&amp;edit_assignment=<?=$assignment['id']?>" title="Modifier" aria-label="Modifier"><i class="bi bi-pencil-square"></i></a><form method="post" onsubmit="return confirm('Supprimer cette affectation et ses évaluations ?')"><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_assignment"><input type="hidden" name="assignment_id" value="<?=$assignment['id']?>"><button class="icon-button danger" title="Supprimer" aria-label="Supprimer"><i class="bi bi-trash"></i></button></form></span></td></tr><?php endforeach?></tbody></table></div></section>
    <section class="panel"><p class="eyebrow"><?=$edit ? 'Modification' : 'Nouvelle affectation'?></p><h2><?=$edit ? 'Modifier l’affectation' : 'Ajouter une matière au niveau ou à un groupe'?></h2><?php render_assignment_form($edit, $classes, $groups, $subjects, $teachers, $classId);?><?php if ($edit):?><div class="actions"><a class="button secondary" href="?page=structure&amp;section=assignments&amp;class_id=<?=$classId?>">Annuler</a></div><?php endif?></section><?php
}

function render_assignments_section_compact(array $assignments, int $classId, array $classes, array $groups, array $subjects, array $teachers): void
{
    $editId = (int)($_GET['edit_assignment'] ?? 0);
    $edit = null;
    foreach ($assignments as $item) {
        if ((int)$item['id'] === $editId) {
            $edit = $item;
        }
    }
    $allLevels = $classId === 0;
    $visible = array_values(array_filter($assignments, fn ($item) => $allLevels || (int)$item['class_id'] === $classId));
    ?><section class="panel assignment-intro"><div class="panel-head"><div><p class="eyebrow">Module administrateur</p><h2>Affectations pédagogiques</h2></div><a class="button <?=$allLevels ? '' : 'secondary'?>" href="?page=structure&amp;section=assignments&amp;class_id=0">Voir toutes les affectations</a></div><form method="get"><input type="hidden" name="page" value="structure"><input type="hidden" name="section" value="assignments"><label>Niveau<select name="class_id" onchange="this.form.submit()"><option value="0" <?=$allLevels ? 'selected' : ''?>>Tous les niveaux</option><?php foreach ($classes as $class):?><option value="<?=$class['id']?>" <?=$classId === (int)$class['id'] ? 'selected' : ''?>><?=e($class['level'])?></option><?php endforeach?></select></label></form></section>
    <details class="panel bulk-assignments"><summary><strong>Créer plusieurs affectations pour un professeur</strong></summary><form method="post"><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="bulk_save_assignments"><label>Professeur<select required name="teacher_id"><option value="">Choisir un professeur</option><?php foreach ($teachers as $teacher):?><option value="<?=$teacher['id']?>"><?=e($teacher['name'])?></option><?php endforeach?></select></label><div class="bulk-assignment-grid"><fieldset><legend>Niveaux concernés</legend><div class="student-checklist"><?php foreach ($classes as $class):?><label class="check"><input type="checkbox" name="class_ids[]" value="<?=$class['id']?>"> <?=e($class['level'])?></label><?php endforeach?></div></fieldset><fieldset><legend>Matières enseignées</legend><div class="student-checklist"><?php foreach ($subjects as $subject):?><label class="check"><input type="checkbox" name="subject_ids[]" value="<?=$subject['id']?>"> <?=e($subject['name'])?></label><?php endforeach?></div></fieldset></div><p class="muted">Une affectation « niveau entier » sera créée pour chaque combinaison sélectionnée, avec le coefficient par défaut de la matière.</p><button>Créer les affectations</button></form></details>
    <div class="two-col assignments-layout"><section class="panel"><div class="panel-head"><div><p class="eyebrow"><?=$allLevels ? 'Vue générale' : 'Niveau sélectionné'?></p><h2><?=$allLevels ? 'Toutes les affectations' : count($visible).' affectation'.(count($visible) > 1 ? 's' : '')?></h2></div><span class="badge"><?=count($visible)?></span></div><div class="table-wrap"><table><thead><tr><?php if ($allLevels):?><th>Niveau</th><?php endif?><th>Ordre</th><th>Matière</th><th>Public</th><th>Professeur(s)</th><th>Coef.</th><th>Actions</th></tr></thead><tbody><?php foreach ($visible as $assignment):?><tr><?php if ($allLevels):?><td><strong><?=e($assignment['level'])?></strong></td><?php endif?><td><?=e($assignment['display_order'])?></td><td><strong><?=e($assignment['subject'])?></strong></td><td><?=e($assignment['group_label'] ?: 'Niveau entier')?></td><td><?=e($assignment['teachers'] ?: 'Sans enseignant')?></td><td><?=e($assignment['assignment_coefficient'])?></td><td><span class="table-actions"><a class="icon-button" href="?page=structure&amp;section=assignments&amp;class_id=<?=$classId?>&amp;edit_assignment=<?=$assignment['id']?>" title="Modifier" aria-label="Modifier"><i class="bi bi-pencil-square"></i></a><form method="post" onsubmit="return confirm('Supprimer cette affectation et ses évaluations ?')"><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_assignment"><input type="hidden" name="assignment_id" value="<?=$assignment['id']?>"><button class="icon-button danger" title="Supprimer" aria-label="Supprimer"><i class="bi bi-trash"></i></button></form></span></td></tr><?php endforeach?><?php if (!$visible):?><tr><td colspan="<?=$allLevels ? 7 : 6?>" class="empty">Aucune affectation à afficher.</td></tr><?php endif?></tbody></table></div></section>
    <aside class="sticky"><section class="panel"><p class="eyebrow"><?=$edit ? 'Modification' : 'Création rapide'?></p><h2><?=$edit ? 'Modifier l’affectation' : 'Nouvelle affectation'?></h2><?php render_assignment_form($edit, $classes, $groups, $subjects, $teachers, $classId);?><?php if ($edit):?><div class="actions"><a class="button secondary" href="?page=structure&amp;section=assignments&amp;class_id=<?=$classId?>">Annuler</a></div><?php endif?></section><div class="panel"><p class="eyebrow">Organisation</p><h2>Groupes et enseignants</h2><div class="actions"><a class="button secondary" href="?page=structure&amp;section=groups">Composer les groupes</a><?php if (is_admin()):?><a class="button secondary" href="?page=users">Gérer les enseignants</a><?php endif?></div></div></aside></div><?php
}
